name: valida_example
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  valida:

dev_dependencies:
  test:
  build_runner:
  valida_generator:
    path: ../../valida_generator/

dependency_overrides:
  valida:
    path: ../../valida/
