name: formgen_generation
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  build:
  source_gen:
  analyzer:
  formgen:
    path: ../formgen/

dev_dependencies:
  build_runner:
  build_config:
  lint: ^1.0.0
  test:
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
