name: valida
description: Create field, params and object validators from code annotations.
version: 0.0.1
homepage: https://github.com/juancastillo0/valida

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  meta: ^1.0.0
  validators: ^3.0.0

dev_dependencies:
  lint: ^1.0.0
  test: ^1.0.0
