name: valida
description: Create field, params and object validators from code annotations.
version: 0.1.0
homepage: https://github.com/juancastillo0/valida

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  collection: ^1.0.0
  meta: ^1.0.0
  validators: ^3.0.0

dev_dependencies:
  lint: ^1.0.0
  test: ^1.0.0
